Fix invalid assert.throws statements
javascriptdata/danfojs pull request #419
Opened 2022-03-08 11:58 UTC by igonro

Closes #416.

- [x] Fix invalid `assert.throws` statements
- [ ] Run the tests again and check that the tests passed

To review: @risenW @steveoni

2022-03-08 12:00 UTC, igonro commented
After fixing the invalid `assert.throws`, some of the node tests are not passing. This is the output:

```
  707 passing (965ms)
  2 failing

  1) DataFrame
       addColumn
         throw error for wrong column length:

      AssertionError: expected [Function] to throw error including 'ParamError: Column data length mismatch. You provided data with length 3 but Ndframe has column of length 4' but got 'ParamError: Column data length mismatch. You provided data with length 3 but Ndframe has column of length 3'
      + expected - actual

      -ParamError: Column data length mismatch. You provided data with length 3 but Ndframe has column of length 3
      +ParamError: Column data length mismatch. You provided data with length 3 but Ndframe has column of length 4

      at Context.<anonymous> (test/core/frame.test.ts:131:20)
      at processImmediate (internal/timers.js:464:21)

  2) Generic (NDFrame)
       NDframe Created from Array
         Throws error on duplicate index:

      AssertionError: expected [Function] to throw error including 'IndexError: Row index must contain unique values' but got 'IndexError: You provided an index of length 3 but Ndframe rows has length of 2'
      + expected - actual

      -IndexError: You provided an index of length 3 but Ndframe rows has length of 2
      +IndexError: Row index must contain unique values

      at Context.<anonymous> (test/core/generic.test.ts:72:20)
      at processImmediate (internal/timers.js:464:21)
```

2022-03-08 12:06 UTC, igonro commented
The same happens for some browser tests:
```
Chrome Headless 98.0.4758.102 (Linux x86_64) DataFrame addColumn throw error for wrong column length FAILED
        AssertionError: expected [Function] to throw error including 'ParamError: Column data length mismatch. You provided data with length 3 but Ndframe has column of length 4' but got 'ParamError: Column data length mismatch. You provided data with length 3 but Ndframe has column of length 3'
            at Context.<anonymous> (/tmp/7ad0f53a5cff4b52986a8d5fc061a919.browserify.js:151280:14)

Chrome Headless 98.0.4758.102 (Linux x86_64) Generic (NDFrame) NDframe Created from Array Throws error on duplicate index FAILED
        AssertionError: expected [Function] to throw error including 'IndexError: Row index must contain unique values' but got 'IndexError: You provided an index of length 3 but Ndframe rows has length of 2'
            at Context.<anonymous> (/tmp/7ad0f53a5cff4b52986a8d5fc061a919.browserify.js:154123:14)
```

2022-03-08 12:20 UTC, igonro commented
I solved those errors. Now all the tests are passing! 🎉 

I'm glad I casually found those `assert.throws` typos while working in #417, because they were hiding a little bug in the `shared/errors.ts` file, and other little bug in the tests of "Throws error on duplicate index" 😄

2022-03-09 08:07 UTC, steveoni requested changes

2022-03-09 08:07 UTC, steveoni commented on src/danfojs-browser/tests/core/frame.test.js
> +      assert.throws(
@igonro can you apply lint fix here, to break into several lines

2022-03-09 08:07 UTC, steveoni commented on src/danfojs-browser/tests/core/generic.test.js
> +      assert.throws(
Same here

2022-03-09 13:20 UTC, igonro commented
Done! @steveoni 
I did it for the js files. Maybe is needed for the ts files too(?)
I looked at some assert.throws, but the lint style is a bit different sometimes.

2022-07-29 06:51 UTC, merged